version: "3.8"

services:
  booking-service:
    build:
      context: ./booking-service
    container_name: booking-service
    ports:
      - "9090:9090"
    networks:
      - hotelio-net
    environment:
      PGHOST: booking-db
      PGPORT: 5432
      PGUSER: booking
      PGPASSWORD: booking
      PGDATABASE: booking
      MONOLITH_BASE_URL: http://monolith:8080
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: booking-events
      GRPC_PORT: 9090
    depends_on:
      - booking-db

  booking-db:
    image: postgres:15
    container_name: booking-db
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking
    ports:
      - "5433:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  booking-history-service:
    build:
      context: ./booking-history-service
    container_name: booking-history-service
    networks:
      - hotelio-net
    environment:
      PGHOST: booking-history-db
      PGPORT: 5432
      PGUSER: history
      PGPASSWORD: history
      PGDATABASE: booking_history
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: booking-events
      KAFKA_GROUP_ID: booking-history-service
    depends_on:
      - kafka
      - booking-history-db

  booking-history-db:
    image: postgres:15
    container_name: booking-history-db
    environment:
      POSTGRES_USER: history
      POSTGRES_PASSWORD: history
      POSTGRES_DB: booking_history
    ports:
      - "5434:5432"
    volumes:
      - booking-history-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

volumes:
  booking-db-data:
  booking-history-db-data:

networks:
  hotelio-net:
    external: true
