{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
spec:
  host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 0
    outlierDetection:
      {{- toYaml .Values.istio.outlierDetection | nindent 6 }}
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
{{- end }}
